[2024-12-20T10:04:47.481+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-20T10:04:47.522+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_insert_news.fetch_and_insert_news_all_countries manual__2024-12-20T10:04:37.555932+00:00 [queued]>
[2024-12-20T10:04:47.542+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_insert_news.fetch_and_insert_news_all_countries manual__2024-12-20T10:04:37.555932+00:00 [queued]>
[2024-12-20T10:04:47.544+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-20T10:04:47.588+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_and_insert_news_all_countries> on 2024-12-20 10:04:37.555932+00:00
[2024-12-20T10:04:47.606+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=698) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-20T10:04:47.612+0000] {standard_task_runner.py:72} INFO - Started process 709 to run task
[2024-12-20T10:04:47.612+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_insert_news', 'fetch_and_insert_news_all_countries', 'manual__2024-12-20T10:04:37.555932+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/snowflake_connector_dag.py', '--cfg-path', '/tmp/tmp6xnuvox8']
[2024-12-20T10:04:47.617+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask fetch_and_insert_news_all_countries
[2024-12-20T10:04:47.723+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_and_insert_news.fetch_and_insert_news_all_countries manual__2024-12-20T10:04:37.555932+00:00 [running]> on host 4fe538676cbc
[2024-12-20T10:04:47.919+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='srush' AIRFLOW_CTX_DAG_ID='fetch_and_insert_news' AIRFLOW_CTX_TASK_ID='fetch_and_insert_news_all_countries' AIRFLOW_CTX_EXECUTION_DATE='2024-12-20T10:04:37.555932+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-20T10:04:37.555932+00:00'
[2024-12-20T10:04:47.928+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-20T10:04:48.052+0000] {base.py:84} INFO - Retrieving connection 'snowflake_con'
[2024-12-20T10:04:48.054+0000] {connection.py:414} INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.12.8, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2024-12-20T10:04:48.061+0000] {connection.py:1197} INFO - Connecting to GLOBAL Snowflake domain
[2024-12-20T10:04:48.063+0000] {connection.py:1278} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-12-20T10:04:49.922+0000] {cursor.py:1166} INFO - Number of results in first chunk: 11
[2024-12-20T10:04:50.033+0000] {cursor.py:1166} INFO - Number of results in first chunk: 5
[2024-12-20T10:04:50.035+0000] {logging_mixin.py:190} INFO - Fetched Keywords: ['currency', 'forex', 'finance', 'disease', 'war', 'election', 'pandemic', 'inflation', 'bank', 'trade', 'treaty']
[2024-12-20T10:04:50.036+0000] {logging_mixin.py:190} INFO - Fetched Countries: ['CH', 'JA', 'NZ', 'SZ', 'RS']
[2024-12-20T10:04:50.037+0000] {logging_mixin.py:190} INFO - Processing news for country: CH
[2024-12-20T10:04:53.040+0000] {logging_mixin.py:190} INFO - Fetching news from 2024-03-13 to 2024-03-14 for CH...
[2024-12-20T10:04:53.941+0000] {logging_mixin.py:190} INFO - Error fetching data for date: 2024-03-13 and country: CH. Error: The gdelt api returned a non-successful statuscode. This is the response message: Please limit requests to one every 5 seconds or contact kalev.leetaru5@gmail.com for larger queries.
[2024-12-20T10:04:56.941+0000] {logging_mixin.py:190} INFO - Fetching news from 2024-03-14 to 2024-03-15 for CH...
[2024-12-20T10:04:57.786+0000] {logging_mixin.py:190} INFO - Error fetching data for date: 2024-03-14 and country: CH. Error: The gdelt api returned a non-successful statuscode. This is the response message: Please limit requests to one every 5 seconds or contact kalev.leetaru5@gmail.com for larger queries.
[2024-12-20T10:05:00.787+0000] {logging_mixin.py:190} INFO - Fetching news from 2024-03-15 to 2024-03-16 for CH...
[2024-12-20T10:05:01.784+0000] {logging_mixin.py:190} INFO - Error fetching data for date: 2024-03-15 and country: CH. Error: The gdelt api returned a non-successful statuscode. This is the response message: Please limit requests to one every 5 seconds or contact kalev.leetaru5@gmail.com for larger queries.
[2024-12-20T10:05:04.786+0000] {logging_mixin.py:190} INFO - Fetching news from 2024-03-16 to 2024-03-17 for CH...
[2024-12-20T10:05:05.701+0000] {logging_mixin.py:190} INFO - Error fetching data for date: 2024-03-16 and country: CH. Error: The gdelt api returned a non-successful statuscode. This is the response message: Please limit requests to one every 5 seconds or contact kalev.leetaru5@gmail.com for larger queries.
[2024-12-20T10:05:08.703+0000] {logging_mixin.py:190} INFO - Fetching news from 2024-03-17 to 2024-03-18 for CH...
[2024-12-20T10:05:09.611+0000] {logging_mixin.py:190} INFO - Error fetching data for date: 2024-03-17 and country: CH. Error: The gdelt api returned a non-successful statuscode. This is the response message: Please limit requests to one every 5 seconds or contact kalev.leetaru5@gmail.com for larger queries.
[2024-12-20T10:05:12.613+0000] {logging_mixin.py:190} INFO - Fetching news from 2024-03-18 to 2024-03-19 for CH...
[2024-12-20T10:05:13.458+0000] {logging_mixin.py:190} INFO - Error fetching data for date: 2024-03-18 and country: CH. Error: The gdelt api returned a non-successful statuscode. This is the response message: Please limit requests to one every 5 seconds or contact kalev.leetaru5@gmail.com for larger queries.
[2024-12-20T10:05:16.460+0000] {logging_mixin.py:190} INFO - Fetching news from 2024-03-19 to 2024-03-20 for CH...
[2024-12-20T10:05:17.300+0000] {logging_mixin.py:190} INFO - Error fetching data for date: 2024-03-19 and country: CH. Error: The gdelt api returned a non-successful statuscode. This is the response message: Please limit requests to one every 5 seconds or contact kalev.leetaru5@gmail.com for larger queries.
[2024-12-20T10:05:18.021+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to restarting. Terminating instance.
[2024-12-20T10:05:18.023+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-20T10:05:18.027+0000] {process_utils.py:132} INFO - Sending 15 to group 709. PIDs of all processes in the group: [709]
[2024-12-20T10:05:18.028+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 709
[2024-12-20T10:05:18.029+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-20T10:05:18.030+0000] {connection.py:789} INFO - closed
[2024-12-20T10:05:18.062+0000] {connection.py:795} INFO - No async queries seem to be running, deleting session
[2024-12-20T10:05:18.119+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/snowflake_connector_dag.py", line 144, in fetch_and_insert_news_for_countries
    time.sleep(3)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-12-20T10:05:18.136+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_and_insert_news, task_id=fetch_and_insert_news_all_countries, run_id=manual__2024-12-20T10:04:37.555932+00:00, execution_date=20241220T100437, start_date=20241220T100447, end_date=20241220T100518
[2024-12-20T10:05:18.168+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-20T10:05:18.243+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=709, status='terminated', exitcode=2, started='10:04:47') (709) terminated with exit code 2
