[2025-01-02T06:37:14.674+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-02T06:37:14.710+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_transform_news_data.fetch_and_insert_news_all_countries manual__2025-01-02T06:37:10.987786+00:00 [queued]>
[2025-01-02T06:37:14.735+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_transform_news_data.fetch_and_insert_news_all_countries manual__2025-01-02T06:37:10.987786+00:00 [queued]>
[2025-01-02T06:37:14.736+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-02T06:37:14.776+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_and_insert_news_all_countries> on 2025-01-02 06:37:10.987786+00:00
[2025-01-02T06:37:14.787+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=156) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-02T06:37:14.795+0000] {standard_task_runner.py:72} INFO - Started process 158 to run task
[2025-01-02T06:37:14.792+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_transform_news_data', 'fetch_and_insert_news_all_countries', 'manual__2025-01-02T06:37:10.987786+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/fetch_and_transform_news.py', '--cfg-path', '/tmp/tmp74hhhoel']
[2025-01-02T06:37:14.798+0000] {standard_task_runner.py:105} INFO - Job 80: Subtask fetch_and_insert_news_all_countries
[2025-01-02T06:37:14.898+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_and_transform_news_data.fetch_and_insert_news_all_countries manual__2025-01-02T06:37:10.987786+00:00 [running]> on host 4fe538676cbc
[2025-01-02T06:37:15.115+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_transform_news_data' AIRFLOW_CTX_TASK_ID='fetch_and_insert_news_all_countries' AIRFLOW_CTX_EXECUTION_DATE='2025-01-02T06:37:10.987786+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-02T06:37:10.987786+00:00'
[2025-01-02T06:37:15.118+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-02T06:37:15.168+0000] {base.py:84} INFO - Retrieving connection 'snowflake_con'
[2025-01-02T06:37:15.171+0000] {connection.py:414} INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.12.8, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-01-02T06:37:15.174+0000] {connection.py:1197} INFO - Connecting to GLOBAL Snowflake domain
[2025-01-02T06:37:15.175+0000] {connection.py:1278} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-01-02T06:37:16.507+0000] {logging_mixin.py:190} INFO - Error inserting data into Snowflake: 250001 (08001): None: Failed to connect to DB: qkjqutz-knb84971.snowflakecomputing.com:443. Incorrect username or password was specified.
[2025-01-02T06:37:16.509+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-02T06:37:16.526+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-02T06:37:16.528+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fetch_and_transform_news_data, task_id=fetch_and_insert_news_all_countries, run_id=manual__2025-01-02T06:37:10.987786+00:00, execution_date=20250102T063710, start_date=20250102T063714, end_date=20250102T063716
[2025-01-02T06:37:16.622+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-02T06:37:16.661+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-02T06:37:16.667+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
