[2025-01-02T06:41:29.134+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-02T06:41:29.164+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_transform_news_data.process_news_all_countries manual__2025-01-02T06:41:25.806474+00:00 [queued]>
[2025-01-02T06:41:29.182+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_transform_news_data.process_news_all_countries manual__2025-01-02T06:41:25.806474+00:00 [queued]>
[2025-01-02T06:41:29.183+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-02T06:41:29.211+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_news_all_countries> on 2025-01-02 06:41:25.806474+00:00
[2025-01-02T06:41:29.223+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=237) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-02T06:41:29.226+0000] {standard_task_runner.py:72} INFO - Started process 242 to run task
[2025-01-02T06:41:29.226+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_transform_news_data', 'process_news_all_countries', 'manual__2025-01-02T06:41:25.806474+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/fetch_and_transform_news.py', '--cfg-path', '/tmp/tmpoziq_npa']
[2025-01-02T06:41:29.230+0000] {standard_task_runner.py:105} INFO - Job 88: Subtask process_news_all_countries
[2025-01-02T06:41:29.310+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_and_transform_news_data.process_news_all_countries manual__2025-01-02T06:41:25.806474+00:00 [running]> on host 4fe538676cbc
[2025-01-02T06:41:29.488+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_transform_news_data' AIRFLOW_CTX_TASK_ID='process_news_all_countries' AIRFLOW_CTX_EXECUTION_DATE='2025-01-02T06:41:25.806474+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-02T06:41:25.806474+00:00'
[2025-01-02T06:41:29.491+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-02T06:41:29.535+0000] {base.py:84} INFO - Retrieving connection 'snowflake_con'
[2025-01-02T06:41:29.541+0000] {connection.py:414} INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.12.8, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-01-02T06:41:29.543+0000] {connection.py:1197} INFO - Connecting to GLOBAL Snowflake domain
[2025-01-02T06:41:29.544+0000] {connection.py:1278} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-01-02T06:41:31.594+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-01-02T06:41:31.595+0000] {logging_mixin.py:190} INFO - None
[2025-01-02T06:41:31.596+0000] {connection.py:789} INFO - closed
[2025-01-02T06:41:31.910+0000] {connection.py:795} INFO - No async queries seem to be running, deleting session
[2025-01-02T06:41:32.244+0000] {connection.py:414} INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.12.8, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-01-02T06:41:32.246+0000] {connection.py:1197} INFO - Connecting to GLOBAL Snowflake domain
[2025-01-02T06:41:32.248+0000] {connection.py:1278} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-01-02T06:41:35.164+0000] {cursor.py:1166} INFO - Number of results in first chunk: 862
[2025-01-02T06:41:37.365+0000] {connection.py:789} INFO - closed
[2025-01-02T06:41:37.670+0000] {connection.py:795} INFO - No async queries seem to be running, deleting session
[2025-01-02T06:41:38.005+0000] {logging_mixin.py:190} INFO - Error transforming data into Snowflake: time data '2020-01-01 00:00:00.000' does not match format '%Y%m%dT%H%M%SZ'
[2025-01-02T06:41:38.008+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-02T06:41:38.025+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-02T06:41:38.027+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fetch_and_transform_news_data, task_id=process_news_all_countries, run_id=manual__2025-01-02T06:41:25.806474+00:00, execution_date=20250102T064125, start_date=20250102T064129, end_date=20250102T064138
[2025-01-02T06:41:38.107+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-02T06:41:38.135+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-02T06:41:38.142+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
