[2024-12-24T12:33:26.121+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-24T12:33:26.157+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: forex_data_flatten.transform_data manual__2024-12-24T12:33:19.105116+00:00 [queued]>
[2024-12-24T12:33:26.175+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: forex_data_flatten.transform_data manual__2024-12-24T12:33:19.105116+00:00 [queued]>
[2024-12-24T12:33:26.176+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-24T12:33:26.205+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform_data> on 2024-12-24 12:33:19.105116+00:00
[2024-12-24T12:33:26.224+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=73492) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-24T12:33:26.239+0000] {standard_task_runner.py:72} INFO - Started process 73494 to run task
[2024-12-24T12:33:26.220+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'forex_data_flatten', 'transform_data', 'manual__2024-12-24T12:33:19.105116+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/flatten.py', '--cfg-path', '/tmp/tmp9ao0iukw']
[2024-12-24T12:33:26.241+0000] {standard_task_runner.py:105} INFO - Job 55: Subtask transform_data
[2024-12-24T12:33:26.504+0000] {task_command.py:467} INFO - Running <TaskInstance: forex_data_flatten.transform_data manual__2024-12-24T12:33:19.105116+00:00 [running]> on host 4fe538676cbc
[2024-12-24T12:33:26.730+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='forex_data_flatten' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-24T12:33:19.105116+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-24T12:33:19.105116+00:00'
[2024-12-24T12:33:26.735+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-24T12:33:26.820+0000] {connection.py:414} INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.12.8, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2024-12-24T12:33:26.828+0000] {connection.py:1197} INFO - Connecting to GLOBAL Snowflake domain
[2024-12-24T12:33:26.831+0000] {connection.py:1278} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-12-24T12:33:27.727+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2024-12-24T12:33:29.310+0000] {logging_mixin.py:190} INFO - Data successfully transformed.
[2024-12-24T12:33:29.312+0000] {connection.py:789} INFO - closed
[2024-12-24T12:33:29.339+0000] {connection.py:795} INFO - No async queries seem to be running, deleting session
[2024-12-24T12:33:29.378+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-24T12:33:29.393+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-24T12:33:29.395+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=forex_data_flatten, task_id=transform_data, run_id=manual__2024-12-24T12:33:19.105116+00:00, execution_date=20241224T123319, start_date=20241224T123326, end_date=20241224T123329
[2024-12-24T12:33:29.485+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-24T12:33:29.512+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-24T12:33:29.517+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
