[2024-12-17T10:19:20.825+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-17T10:19:20.983+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag_v3.second_task scheduled__2024-12-16T01:02:00+00:00 [queued]>
[2024-12-17T10:19:21.050+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag_v3.second_task scheduled__2024-12-16T01:02:00+00:00 [queued]>
[2024-12-17T10:19:21.052+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2024-12-17T10:19:21.310+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): second_task> on 2024-12-16 01:02:00+00:00
[2024-12-17T10:19:21.332+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2049) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-17T10:19:21.341+0000] {standard_task_runner.py:72} INFO - Started process 2081 to run task
[2024-12-17T10:19:21.348+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag_v3', 'second_task', 'scheduled__2024-12-16T01:02:00+00:00', '--job-id', '228', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmpcj4yka_c']
[2024-12-17T10:19:21.358+0000] {standard_task_runner.py:105} INFO - Job 228: Subtask second_task
[2024-12-17T10:19:21.765+0000] {task_command.py:467} INFO - Running <TaskInstance: my_first_dag_v3.second_task scheduled__2024-12-16T01:02:00+00:00 [running]> on host 8348eb091483
[2024-12-17T10:19:22.332+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='srush' AIRFLOW_CTX_DAG_ID='my_first_dag_v3' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-16T01:02:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-16T01:02:00+00:00'
[2024-12-17T10:19:22.344+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-17T10:19:22.395+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2024-12-17T10:19:22.400+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo task2 runs after task1']
[2024-12-17T10:19:22.539+0000] {subprocess.py:99} INFO - Output:
[2024-12-17T10:19:22.542+0000] {subprocess.py:106} INFO - task2 runs after task1
[2024-12-17T10:19:22.550+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2024-12-17T10:19:22.681+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-17T10:19:22.695+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_first_dag_v3, task_id=second_task, run_id=scheduled__2024-12-16T01:02:00+00:00, execution_date=20241216T010200, start_date=20241217T101920, end_date=20241217T101922
[2024-12-17T10:19:22.899+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-17T10:19:22.977+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
