[2024-12-18T11:53:34.249+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-18T11:53:34.272+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: snowflake_connection_check.check_snowflake_connection manual__2024-12-18T11:53:32.167071+00:00 [queued]>
[2024-12-18T11:53:34.285+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: snowflake_connection_check.check_snowflake_connection manual__2024-12-18T11:53:32.167071+00:00 [queued]>
[2024-12-18T11:53:34.286+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-18T11:53:34.310+0000] {taskinstance.py:2889} INFO - Executing <Task(SnowflakeOperator): check_snowflake_connection> on 2024-12-18 11:53:32.167071+00:00
[2024-12-18T11:53:34.320+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1747) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-18T11:53:34.322+0000] {standard_task_runner.py:72} INFO - Started process 1749 to run task
[2024-12-18T11:53:34.323+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'snowflake_connection_check', 'check_snowflake_connection', 'manual__2024-12-18T11:53:32.167071+00:00', '--job-id', '2572', '--raw', '--subdir', 'DAGS_FOLDER/snowflake_connector_dag.py', '--cfg-path', '/tmp/tmpzzv0mo43']
[2024-12-18T11:53:34.326+0000] {standard_task_runner.py:105} INFO - Job 2572: Subtask check_snowflake_connection
[2024-12-18T11:53:34.393+0000] {task_command.py:467} INFO - Running <TaskInstance: snowflake_connection_check.check_snowflake_connection manual__2024-12-18T11:53:32.167071+00:00 [running]> on host 8348eb091483
[2024-12-18T11:53:34.526+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='snowflake_connection_check' AIRFLOW_CTX_TASK_ID='check_snowflake_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-12-18T11:53:32.167071+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-18T11:53:32.167071+00:00'
[2024-12-18T11:53:34.529+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-18T11:53:34.548+0000] {sql.py:278} INFO - Executing:  select current_database();
[2024-12-18T11:53:34.563+0000] {base.py:84} INFO - Retrieving connection 'snowflake_con'
[2024-12-18T11:53:34.577+0000] {base.py:84} INFO - Retrieving connection 'snowflake_con'
[2024-12-18T11:53:34.579+0000] {connection.py:414} INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.12.8, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2024-12-18T11:53:34.580+0000] {connection.py:1197} INFO - Connecting to GLOBAL Snowflake domain
[2024-12-18T11:53:34.582+0000] {connection.py:1278} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-12-18T11:53:35.138+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2024-12-18T11:53:35.139+0000] {sql.py:553} INFO - Running statement: select current_database();, parameters: None
[2024-12-18T11:53:35.207+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2024-12-18T11:53:35.208+0000] {sql.py:562} INFO - Rows affected: 1
[2024-12-18T11:53:35.210+0000] {snowflake.py:447} INFO - Rows affected: 1
[2024-12-18T11:53:35.212+0000] {snowflake.py:448} INFO - Snowflake query id: 01b91ca9-0000-d1e7-0008-6fb60004ddae
[2024-12-18T11:53:35.266+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2024-12-18T11:53:35.267+0000] {connection.py:789} INFO - closed
[2024-12-18T11:53:35.299+0000] {connection.py:795} INFO - No async queries seem to be running, deleting session
[2024-12-18T11:53:35.370+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-18T11:53:35.372+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=snowflake_connection_check, task_id=check_snowflake_connection, run_id=manual__2024-12-18T11:53:32.167071+00:00, execution_date=20241218T115332, start_date=20241218T115334, end_date=20241218T115335
[2024-12-18T11:53:35.422+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-18T11:53:35.449+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-18T11:53:35.454+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
